### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by saidvandeklundert** [Juniper/jetez#12]
The link in the readme gives me a 404:

https://www.juniper.net/documentation/en_US/jet19.4/topics/topic-map/jet-app-development-prerequisites.html#id-jet-certificate-request

**Comment by ydnath** [comment]
Update the readme to use https://www.juniper.net/documentation/us/en/software/junos/jet-developer/topics/topic-map/jet-on-device-applications.html#id-develop-signed-jet-applications__id-jet-certificate-request
